server:
  port: ${SERVER_PORT:8005}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:account-backend}
  
  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
  
  # JPA Configuration
  jpa:
    database: ${SPRING_JPA_DATABASE:h2}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL:true}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
        dialect: ${SPRING_DATASOURCE_DIALECT:org.hibernate.dialect.H2Dialect}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW:false}
  
  # H2 Console (Development only)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Redis Configuration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

# Kakao OAuth Configuration
kakao:
  client-id: ${KAKAO_CLIENT_ID:your_kakao_client_id}
  client-secret: ${KAKAO_CLIENT_SECRET:your_kakao_client_secret}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# Logging
logging:
  level:
    com.myrealpet: DEBUG
    org.springframework.security: DEBUG