server:
  port: ${SERVER_PORT:8005}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:account-backend}
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  # JPA Configuration
  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  
  # H2 Console (Development only)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Redis Configuration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}

# Kakao OAuth Configuration
kakao:
  client-id: ${KAKAO_CLIENT_ID:your_kakao_client_id}
  client-secret: ${KAKAO_CLIENT_SECRET:your_kakao_client_secret}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# Logging
logging:
  level:
    com.myrealpet: DEBUG
    org.springframework.security: DEBUG